package sop_corba.GestionPacientesPackage;


/**
* sop_corba/GestionPacientesPackage/pacienteDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from paciente_operaciones.idl
* jueves 30 de noviembre de 2023 12:27:28 PM COT
*/

public final class pacienteDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int noHabitacion = (int)0;
  public String nombres = null;
  public String apellidos = null;
  public String tipoEdad = null;
  public int cantEdad = (int)0;

  public pacienteDTO ()
  {
  } // ctor

  public pacienteDTO (int _noHabitacion, String _nombres, String _apellidos, String _tipoEdad, int _cantEdad)
  {
    noHabitacion = _noHabitacion;
    nombres = _nombres;
    apellidos = _apellidos;
    tipoEdad = _tipoEdad;
    cantEdad = _cantEdad;
  } // ctor

    public int getNoHabitacion() {
        return noHabitacion;
    }

    public void setNoHabitacion(int noHabitacion) {
        this.noHabitacion = noHabitacion;
    }

    public String getNombres() {
        return nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getApellidos() {
        return apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getTipoEdad() {
        return tipoEdad;
    }

    public void setTipoEdad(String tipoEdad) {
        this.tipoEdad = tipoEdad;
    }

    public int getCantEdad() {
        return cantEdad;
    }

    public void setCantEdad(int cantEdad) {
        this.cantEdad = cantEdad;
    }
} // class pacienteDTO
