package sop_corba.GestionPacientesPackage;


/**
* sop_corba/GestionPacientesPackage/pacienteDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from paciente_operaciones.idl
* jueves 30 de noviembre de 2023 12:28:27 PM COT
*/

public final class pacienteDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int noHabitacion = (int)0;
  public String nombres = null;
  public String apellidos = null;
  public String tipoEdad = null;
  public int cantEdad = (int)0;

  public pacienteDTO ()
  {
  } // ctor

  public pacienteDTO (int _noHabitacion, String _nombres, String _apellidos, String _tipoEdad, int _cantEdad)
  {
    noHabitacion = _noHabitacion;
    nombres = _nombres;
    apellidos = _apellidos;
    tipoEdad = _tipoEdad;
    cantEdad = _cantEdad;
  } // ctor

} // class pacienteDTO
