package sop_corba;


/**
* sop_corba/GestionPacientesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from paciente_operaciones.idl
* jueves 30 de noviembre de 2023 12:27:28 PM COT
*/

public interface GestionPacientesOperations 
{
  boolean registrarPaciente (sop_corba.GestionPacientesPackage.pacienteDTO objPaciente);
  sop_corba.GestionPacientesPackage.pacienteDTO consultarPaciente (int noHabitacion);
} // interface GestionPacientesOperations
