package sop_corba;

import sop_corba.GestionPacientesPackage.pacienteDTO;


/**
* sop_corba/GestionPacientesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from paciente_operaciones.idl
* jueves 30 de noviembre de 2023 12:28:27 PM COT
*/

public interface GestionPacientesOperations 
{
  boolean registrarPaciente (pacienteDTO objPaciente);
  pacienteDTO consultarPaciente (int noHabitacion);
} // interface GestionPacientesOperations
