package sop_corba;


/**
* sop_corba/GestionPacientes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from paciente_operaciones.idl
* jueves 30 de noviembre de 2023 12:28:27 PM COT
*/

public interface GestionPacientes extends GestionPacientesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionPacientes
